import { useState } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/ui/form";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";
import { useToast } from "@/hooks/use-toast";
import { useWallet } from "@/hooks/useWallet";
import { Loader2, Upload, ExternalLink, AlertTriangle } from "lucide-react";
import { certificateService, PrivacyFirstCertificateIssueRequest } from "@/lib/certificateService";

const createCertificateSchema = z.object({
  // Privacy-First: Only wallet address (DID auto-generated by backend)
  studentWalletAddress: z.string().min(42, "Please enter a valid wallet address").max(42, "Please enter a valid wallet address"),
  
  // Personal data to be wrapped (temporary, for IPFS storage)
  studentName: z.string().min(2, "Student name must be at least 2 characters"),
  studentEmail: z.string().email("Please enter a valid email address"),
  
  // Course information
  courseName: z.string().min(2, "Course name must be at least 2 characters"),
  grade: z.string().min(1, "Grade is required"),
  completionDate: z.string().min(1, "Completion date is required"),
  description: z.string().optional(),
  certificateType: z.string().min(1, "Certificate type is required"),
});

type CreateCertificateForm = z.infer<typeof createCertificateSchema>;

interface CreateCertificateModalProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

export default function CreateCertificateModal({ open, onOpenChange }: CreateCertificateModalProps) {
  const [isUploading, setIsUploading] = useState(false);
  const [uploadedFile, setUploadedFile] = useState<File | null>(null);
  const { toast } = useToast();
  const { mintCertificate, walletAddress, isConnected, connect, isLoading: walletLoading } = useWallet();
  const isLoading = walletLoading;
  const queryClient = useQueryClient();

  const form = useForm<CreateCertificateForm>({
    resolver: zodResolver(createCertificateSchema),
    defaultValues: {
      studentWalletAddress: "",
      studentName: "",
      studentEmail: "",
      courseName: "",
      grade: "",
      completionDate: "",
      description: "",
      certificateType: "",
    },
  });

  const createCertificateMutation = useMutation({
    mutationFn: async (data: CreateCertificateForm) => {
      // Privacy-First Flow (Backend auto-generates DID):
      // 1. Backend generates Student DID from wallet: did:educreds:student:hash(walletAddress)
      // 2. Wraps personal data in DID document
      // 3. Stores DID document on IPFS
      // 4. Creates W3C credential on IPFS
      // 5. Stores only DIDs and IPFS hashes in database
      
      const privacyFirstRequest: PrivacyFirstCertificateIssueRequest = {
        studentWalletAddress: data.studentWalletAddress,
        studentName: data.studentName,
        studentEmail: data.studentEmail,
        courseName: data.courseName,
        grade: data.grade,
        completionDate: data.completionDate,
        certificateType: data.certificateType,
        description: data.description,
        certificatePDF: uploadedFile || undefined,
      };

      // Use privacy-first service (backend handles DID generation)
      const certificateResponse = await certificateService.issueCertificatePrivacyFirst(privacyFirstRequest);
      
      return certificateResponse;
    },
    onSuccess: (data) => {
      toast({
        title: "Certificate issued successfully!",
        description: `Student DID auto-generated from wallet. Data stored securely on IPFS.`,
      });
      
      // Invalidate queries to refresh lists and stats
      queryClient.invalidateQueries({ queryKey: ["/api/certificates/institution"] });
      queryClient.invalidateQueries({ queryKey: ["/api/stats"] });
      
      // Reset form and close modal
      form.reset();
      setUploadedFile(null);
      onOpenChange(false);
    },
    onError: (error: any) => {
      toast({
        title: "Failed to issue certificate",
        description: error.message || "An error occurred while issuing the certificate.",
        variant: "destructive",
      });
    },
  });

  const handleFileUpload = async (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file) return;

    setIsUploading(true);
    try {
      // Store the file for later upload during certificate issuance
      setUploadedFile(file);
      
      toast({
        title: "File selected",
        description: `${file.name} ready for upload during certificate issuance`,
      });
    } catch (error: any) {
      toast({
        title: "File selection failed",
        description: error.message || "Failed to select file.",
        variant: "destructive",
      });
    } finally {
      setIsUploading(false);
    }
  };

  const onSubmit = (data: CreateCertificateForm) => {
    createCertificateMutation.mutate(data);
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>Issue New Certificate (Privacy-First)</DialogTitle>
          <DialogDescription>
            Issue a certificate using privacy-first architecture. Student DID will be auto-generated from wallet address. 
            Personal data will be wrapped in DID documents and stored on IPFS. 
            Only DIDs and IPFS hashes are stored in the database.
          </DialogDescription>
        </DialogHeader>

        <Form {...form}>
          <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-4">
            {/* Student Identification - Wallet Only (DID Auto-Generated) */}
            <div className="space-y-4">
              <h3 className="text-lg font-medium">Student Identification</h3>
              <p className="text-sm text-gray-600">
                Student DID will be automatically generated by the backend from the wallet address using: <code className="bg-gray-100 px-2 py-1 rounded text-xs">did:educreds:student:hash(walletAddress)</code>
              </p>
              
              <FormField
                control={form.control}
                name="studentWalletAddress"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Student Wallet Address *</FormLabel>
                    <FormControl>
                      <Input 
                        placeholder="0x..." 
                        {...field} 
                        data-testid="input-student-address"
                        className="font-mono text-sm"
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
            </div>

            {/* Personal Data to be Wrapped in DID Document */}
            <div className="space-y-4">
              <div className="bg-blue-50 border border-blue-200 rounded-lg p-3">
                <p className="text-sm text-blue-900 font-medium">
                  💾 Data below will be wrapped in DID document and stored on IPFS, NOT in the database
                </p>
              </div>
              
              <h3 className="text-lg font-medium">Student Personal Information (For DID Wrapping)</h3>
              
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <FormField
                  control={form.control}
                  name="studentName"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Student Name *</FormLabel>
                      <FormControl>
                        <Input 
                          placeholder="Enter student's full name" 
                          {...field} 
                          data-testid="input-student-name"
                        />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                <FormField
                  control={form.control}
                  name="studentEmail"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Student Email *</FormLabel>
                      <FormControl>
                        <Input 
                          type="email"
                          placeholder="student@example.com" 
                          {...field} 
                          data-testid="input-student-email"
                        />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />
              </div>
            </div>

            {/* Course Information */}
            <div className="space-y-4">
              <h3 className="text-lg font-medium">Course Information</h3>
              
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <FormField
                  control={form.control}
                  name="courseName"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Course Name *</FormLabel>
                      <FormControl>
                        <Input 
                          placeholder="e.g., Computer Science Degree" 
                          {...field} 
                          data-testid="input-course-name"
                        />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                <FormField
                  control={form.control}
                  name="grade"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Grade/Result *</FormLabel>
                      <FormControl>
                        <Input 
                          placeholder="e.g., A+, Distinction, 85%" 
                          {...field} 
                          data-testid="input-grade"
                        />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />
              </div>

              <FormField
                control={form.control}
                name="completionDate"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Completion Date *</FormLabel>
                    <FormControl>
                      <Input 
                        type="date" 
                        {...field} 
                        data-testid="input-completion-date"
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />

              <FormField
                control={form.control}
                name="description"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Additional Notes</FormLabel>
                    <FormControl>
                      <Textarea 
                        placeholder="Optional additional information about the certificate..."
                        rows={3}
                        {...field} 
                        data-testid="input-description"
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
            </div>

            {/* Certificate Type */}
            <div className="space-y-4">
              <h3 className="text-lg font-medium">Certificate Type</h3>
              
              <FormField
                control={form.control}
                name="certificateType"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Certificate Type *</FormLabel>
                    <FormControl>
                      <select
                        {...field}
                        required
                        className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"
                        data-testid="input-certificate-type"
                      >
                        <option value="">Select type</option>
                        <option value="certificate">Certificate</option>
                        <option value="diploma">Diploma</option>
                        <option value="bachelors">Bachelors</option>
                        <option value="masters">Masters</option>
                        <option value="phd">PhD</option>
                      </select>
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
            </div>

            {/* Document Upload */}
            <div className="space-y-4">
              <h3 className="text-lg font-medium">Certificate Document</h3>
              
              <div className="border-2 border-dashed border-gray-300 rounded-lg p-6">
                <div className="text-center">
                  {uploadedFile ? (
                    <div className="space-y-2">
                      <div className="text-green-600 font-medium">
                        âœ“ {uploadedFile.name}
                      </div>
                      <div className="text-sm text-gray-600">
                        File size: {(uploadedFile.size / 1024 / 1024).toFixed(2)} MB
                      </div>
                    </div>
                  ) : (
                    <div className="space-y-2">
                      <Upload className="mx-auto h-12 w-12 text-gray-400" />
                      <div className="text-sm text-gray-600">
                        Upload certificate document (PDF, PNG, JPG)
                      </div>
                    </div>
                  )}
                  
                  <input
                    type="file"
                    onChange={handleFileUpload}
                    accept=".pdf,.png,.jpg,.jpeg"
                    className="mt-4"
                    disabled={isUploading}
                    data-testid="input-file-upload"
                  />
                  
                  {isUploading && (
                    <div className="mt-2 text-sm text-blue-600">
                      Uploading to IPFS...
                    </div>
                  )}
                </div>
              </div>
            </div>

            <DialogFooter>
              <Button 
                type="button" 
                variant="outline" 
                onClick={() => onOpenChange(false)}
                disabled={createCertificateMutation.isPending}
                data-testid="button-cancel-certificate"
              >
                Cancel
              </Button>
              <Button 
                type="submit" 
                disabled={createCertificateMutation.isPending || isUploading}
                data-testid="button-issue-certificate"
              >
                {createCertificateMutation.isPending ? (
                  <>
                    <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                    Issuing Certificate...
                  </>
                ) : (
                  "Issue Certificate"
                )}
              </Button>
            </DialogFooter>
          </form>
        </Form>
      </DialogContent>
    </Dialog>
  );
}